### ISSUE TITLE
Integrating ZKSM with Hyperledger Indy (A decentralized identity platform)

### ISSUE THREAD

**Issue by nathanawmk** [ing-bank/zkproofs#14]
Hello, I am keen to integrate ZKSM with Hyperledger Indy (A decentralized identity platform). Any idea if there is any work around this? 

Nathan Aw

**Comment by nathanawmk** [comment]
That will be really cool

Nathan Aw

**Comment by ArthurManz** [comment]
How is this conversation going @eduardomoraesdemorais @peter-rutgers @nathanawmk? 
Really exited about this integration. :raised_hands:

**Comment by eduardomoraesdemorais** [comment]
Hi all,

Nathan was proposing us to use ZKSM as another plugin to anonoymous credentials.
Some days ago I played a little bit with the bilinear pairing implementation they have, and it can be perfectly used to implement the ccs08 proposal for ZKSM. Then yes, it is feasible.
@nathanawmk, have you evolved with your initial ideas?
Regards,

**Comment by nathanawmk** [comment]
Hello, apologies work caught up. Yes lets get into a call and see how we
can work on this together. When will be a good time?

Nathan Aw

**Comment by mvdbos** [comment]
@nathanawmk @peter-rutgers  Please check here and reopen the discussion there if you think it is still useful: https://github.com/ing-bank/bulletproofs. We are happy to have a look. This repo will be archived.
