### ISSUE TITLE
Plans on serializing ZKSM Params and Proofs

### ISSUE THREAD

**Issue by drbh** [ing-bank/zkproofs#18]
Hey zkproofs team!

Great work on the ZKSM implementation. Although I had to dig around the repo and look at this [issue](https://github.com/ing-bank/zkproofs/issues/13) to find the relevant code.

I was hoping to make some REST available endpoints to setup, prove and verify as ZKSM, however many of the needed Params are not exportable (need a capital Name to be exportable). This make it impossible to serialize the data, and subsequently separate the prover and verifier.  

After forking the repo I made those variables exportable but didn't want to make a PR because this may conflict some **pre existing serialization plans?** [fork diff](https://github.com/ing-bank/zkproofs/compare/master...drbh:master)

Using this forked repo I created a simple REST service for zkproofs [here](https://github.com/drbh/zksm-examples) that simulates a prover and verifier interaction.

**Comment by eduardomoraesdemorais** [comment]
Hi,

Thank you for your message. I appreciate your work and it should be useful for a lot of people. However we are restructuring the repository, and then we would not be able to merge your ideas right now. But we will consider this issue in the refactoring in order to make those fields exportable. 

Regards,

**Comment by mvdbos** [comment]
@drbh Please check here and reopen the discussion there if you think it is useful. We are happy to have a look. This repo will be archived.

**Comment by mvdbos** [comment]
Oops, left out link: https://github.com/ing-bank/bulletproofs.
Also see the README for how we do JSON serialization.
