### ISSUE TITLE
ZKRP able to work/interoperate with Quorum?

### ISSUE THREAD

**Issue by nathanawmk** [ing-bank/zkproofs#8]
Amazing work there with ZKRP! Quick question - Can Quorum work/interoperate with ZKRP?

**Comment by ArthurManz** [comment]
Yes @nathanawmk , you can use the solidity code to benefit from ZKRP on any Ethereum platform, including Quorum. Also you could use the GO implementation if you have the option to modify the client.

**Comment by yjjnls** [comment]
@ArthurManz I wonder where's the go implementation of ZKRP? And in the `examples/java/zkrp/README.md` , it says "Make sure that the modified Geth is running", while there's no introduction of modified Geth

**Comment by mvdbos** [comment]
Please check here and reopen the discussion there if you think it is still useful: https://github.com/ing-bank/bulletproofs. We are happy to have a look. This repo will be archived.

That repo is only the Go implementation.
