### ISSUE TITLE
Examples of use cases & scaling concerns

### ISSUE THREAD

**Issue by ealemda2** [ing-bank/zkproofs#9]
Could you provide any resources that demonstrate, or give insight into implementing this for example use cases and scaling up? Even the precompiled contract seemed to be too costly to be viable.

**Comment by ArthurManz** [comment]
Hi @ealemda2 we are currently working on different use case / examples using both ZKP. I will let you know as soon as it is done. Let us know if you are working on a use case using our ZKP, maybe we could help you meanwhile we are still working on our examples. If you would like feel free to submit a PR. :smile:

**Comment by mvdbos** [comment]
Please check here and reopen the discussion there if you think it is still useful: https://github.com/ing-bank/bulletproofs. We are happy to have a look. This repo will be archived.
